name: release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true
        default: "X.Y.Z"

jobs:
  lightning-java:
    runs-on: ubuntu-latest
    if: github.repository == 'aerokube/lightning-java'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSWORD

      - name: Deploy release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSWORD: ${{ secrets.MAVEN_GPG_PASSWORD }}
        run: |
          git config user.name $GITHUB_REPOSITORY
          git config user.email "aerokube@aerokube.github.com"
          mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${{ github.event.inputs.releaseVersion }}
          git commit -am "Updated version to ${{ github.event.inputs.releaseVersion }}"
          git push origin master
          git tag ${{ github.event.inputs.releaseVersion }}
          git push origin ${{ github.event.inputs.releaseVersion }}
          mvn clean deploy -P release
          mvn versions:set -DgenerateBackupPoms=false -DnextSnapshot=true
          git commit -am "Updated version to next snapshot"
          git push origin master